In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/content/drive/MyDrive/2022/CNU/ML/Iris.csv')
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [5]:
data.head()
data.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [7]:
del data['Id']

data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
data.mean(), data.std()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

(SepalLengthCm    5.843333
 SepalWidthCm     3.054000
 PetalLengthCm    3.758667
 PetalWidthCm     1.198667
 dtype: float64, SepalLengthCm    0.828066
 SepalWidthCm     0.433594
 PetalLengthCm    1.764420
 PetalWidthCm     0.763161
 dtype: float64)

In [10]:
data.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [12]:
data.loc[:3, :"SepalWidthCm"]

   SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1

In [13]:
data.iloc[:3, :-1]

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2

In [14]:
normal_data = (data.iloc[:, : -1] - data.iloc[:, :-1].mean()) / data.iloc[:, :-1].std()
normal_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.897674      1.028611      -1.336794     -1.308593
1        -1.139200     -0.124540      -1.336794     -1.308593
2        -1.380727      0.336720      -1.393470     -1.308593
3        -1.501490      0.106090      -1.280118     -1.308593
4        -1.018437      1.259242      -1.336794     -1.308593
..             ...           ...            ...           ...
145       1.034539     -0.124540       0.816888      1.443121
146       0.551486     -1.277692       0.703536      0.918985
147       0.793012     -0.124540       0.816888      1.050019
148       0.430722      0.797981       0.930239      1.443121
149       0.068433     -0.124540       0.760212      0.787951

[150 rows x 4 columns]

In [19]:
index = np.where(data['SepalLengthCm'] > 6.0)
index

(array([ 50,  51,  52,  54,  56,  58,  63,  65,  68,  71,  72,  73,  74,
         75,  76,  77,  86,  87,  91,  97, 100, 102, 103, 104, 105, 107,
        108, 109, 110, 111, 112, 115, 116, 117, 118, 120, 122, 123, 124,
        125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        139, 140, 141, 143, 144, 145, 146, 147, 148]),)

In [20]:
data.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [21]:
data.Species.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [22]:
target_dict = {}

for i, v in enumerate(data.Species.unique()):
  target_dict[i] = v

target_dict

{0: 'Iris-setosa', 1: 'Iris-versicolor', 2: 'Iris-virginica'}

In [24]:
label_encoded_species = pd.Series([None for i in range(data.shape[0])])

for i in range(len(target_dict)):
  label_encoded_species[data['Species'] == target_dict[i]] = i

print(data['Species'][0], label_encoded_species[0])
print(data['Species'][50], label_encoded_species[50])
print(data['Species'][100], label_encoded_species[100])

Iris-setosa 0
Iris-versicolor 1
Iris-virginica 2

In [26]:
from sklearn.preprocessing import LabelEncoder

label_encoded_series_sklearn = LabelEncoder().fit_transform(data[['Species']])
label_encoded_series_sklearn

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
from sklearn.preprocessing import OneHotEncoder

df = OneHotEncoder(sparse=False).fit_transform(data[['Species']])

print(data['Species'][0], df[0])
print(data['Species'][50], df[50])
print(data['Species'][100], df[100])

Iris-setosa [1. 0. 0.]
Iris-versicolor [0. 1. 0.]
Iris-virginica [0. 0. 1.]

In [31]:
label = pd.DataFrame(df, columns=data.Species.unique(), dtype=int)
label

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [32]:
data = pd.concat([data.iloc[:, :-1], label], axis=1)
data

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-setosa,Iris-versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [33]:
data = data.reset_index(drop=True)
data

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-setosa,Iris-versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [34]:
data.to_csv('new_Iris.csv', index=False)